name = "anseba-travel"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
workers_dev = false

[assets]
directory = ".open-next/assets"
not_found_handling = "single-page-application"

[[routes]]
pattern = "ansebatraveltour.com/*"
zone_name = "ansebatraveltour.com"

[[routes]]
pattern = "www.ansebatraveltour.com/*"
zone_name = "ansebatraveltour.com"
